//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace FXBusinessLogic.fx_mind {

	[Persistent(@"currency")]
	public partial class DBCurrency : XPLiteObject {
		short fID;
		[Key]
		public short ID {
			get { return fID; }
			set { SetPropertyValue<short>("ID", ref fID, value); }
		}
		string fName;
		[Size(20)]
		public string Name {
			get { return fName; }
			set { SetPropertyValue<string>("Name", ref fName, value); }
		}
		bool fEnabled;
		public bool Enabled {
			get { return fEnabled; }
			set { SetPropertyValue<bool>("Enabled", ref fEnabled, value); }
		}
		[Association(@"DBNewseventReferencesDBCurrency", typeof(DBNewsEvent))]
		public XPCollection<DBNewsEvent> DBNewsevents { get { return GetCollection<DBNewsEvent>("DBNewsevents"); } }
	}

}
