//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace FXBusinessLogic.fx_mind {

	[Persistent(@"newsevent")]
	public partial class DBNewsEvent : XPLiteObject {
		int fID;
		[Key(true)]
		public int ID {
			get { return fID; }
			set { SetPropertyValue<int>("ID", ref fID, value); }
		}
		DBCurrency fCurrencyId;
		[Association(@"DBNewseventReferencesDBCurrency")]
		public DBCurrency CurrencyId {
			get { return fCurrencyId; }
			set { SetPropertyValue<DBCurrency>("CurrencyId", ref fCurrencyId, value); }
		}
		DateTime fHappenTime;
		public DateTime HappenTime {
			get { return fHappenTime; }
			set { SetPropertyValue<DateTime>("HappenTime", ref fHappenTime, value); }
		}
		string fName;
		[Size(500)]
		public string Name {
			get { return fName; }
			set { SetPropertyValue<string>("Name", ref fName, value); }
		}
		byte fImportance;
		public byte Importance {
			get { return fImportance; }
			set { SetPropertyValue<byte>("Importance", ref fImportance, value); }
		}
		string fActualVal;
		[Size(127)]
		public string ActualVal {
			get { return fActualVal; }
			set { SetPropertyValue<string>("ActualVal", ref fActualVal, value); }
		}
		string fForecastVal;
		[Size(127)]
		public string ForecastVal {
			get { return fForecastVal; }
			set { SetPropertyValue<string>("ForecastVal", ref fForecastVal, value); }
		}
		string fPreviousVal;
		[Size(127)]
		public string PreviousVal {
			get { return fPreviousVal; }
			set { SetPropertyValue<string>("PreviousVal", ref fPreviousVal, value); }
		}
		DateTime fParseTime;
		public DateTime ParseTime {
			get { return fParseTime; }
			set { SetPropertyValue<DateTime>("ParseTime", ref fParseTime, value); }
		}
		bool fRaised;
		public bool Raised {
			get { return fRaised; }
			set { SetPropertyValue<bool>("Raised", ref fRaised, value); }
		}
		double fIndicatorValue;
		public double IndicatorValue {
			get { return fIndicatorValue; }
			set { SetPropertyValue<double>("IndicatorValue", ref fIndicatorValue, value); }
		}
	}

}
