//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace FXBusinessLogic.fx_mind {

	[Persistent(@"settings")]
	public partial class DBSettings : XPLiteObject {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
		string fPropertyName;
		//[Key]
		[Size(255)]
		public string PropertyName {
			get { return fPropertyName; }
			set { SetPropertyValue<string>("PropertyName", ref fPropertyName, value); }
		}
		string fValue;
		[Size(SizeAttribute.Unlimited)]
		public string Value {
			get { return fValue; }
			set { SetPropertyValue<string>("Value", ref fValue, value); }
		}
		string fDescription;
		[Size(SizeAttribute.Unlimited)]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
	}

}
