//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace FXBusinessLogic.fx_mind {

	[Persistent(@"site")]
	public partial class DBSite : XPLiteObject {
		int fID;
		[Key]
		public int ID {
			get { return fID; }
			set { SetPropertyValue<int>("ID", ref fID, value); }
		}
		string fName;
		[Size(50)]
		public string Name {
			get { return fName; }
			set { SetPropertyValue<string>("Name", ref fName, value); }
		}
		string fDescription;
		[Size(255)]
		public string Description {
			get { return fDescription; }
			set { SetPropertyValue<string>("Description", ref fDescription, value); }
		}
	}

}
