//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"techindicator")]
    public partial class DBTechIndicator : XPLiteObject
    {
        short fID;
        [Key]
        public short ID
        {
            get { return fID; }
            set { SetPropertyValue<short>("ID", ref fID, value); }
        }
        string fIndicatorName;
        [Size(50)]
        public string IndicatorName
        {
            get { return fIndicatorName; }
            set { SetPropertyValue<string>("IndicatorName", ref fIndicatorName, value); }
        }
        bool fEnabled;
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>("Enabled", ref fEnabled, value); }
        }
    }

}
