/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BusinessObjects
{
  public enum ENUM_ORDERROLE
  {
    RegularTrail = 0,
    GridHead = 1,
    GridTail = 2,
    ShouldBeClosed = 3,
    History = 4,
  }
}
