/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace BusinessObjects
{

    public class ExpertInfo
    {
        public string Account { get; set; }
        public long Magic { get; set; }
        public long Flags { get; set; }
        public string ChartTimeFrame { get; set; }
        public string Symbol { get; set; }
        public string EAName { get; set; }
        public string Data { get; set; }
        public bool IsMaster { get; set; }
        public string OrderTicketsToLoad { get; set; }
        public string Reason { get; set; }
    }
}