/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace BusinessObjects
{
  public static class fxmindConstants
  {
    /// <summary>
    /// Thrift also lets you define constants for use across languages. Complex
    /// types and structs are specified using JSON notation.
    /// </summary>
    public static double GAP_VALUE = -125;
    public static string MTDATETIMEFORMAT = "yyyy.MM.dd HH:mm";
    public static string MYSQLDATETIMEFORMAT = "yyyy-MM-dd HH:mm:ss";
    public static string SOLRDATETIMEFORMAT = "yyyy-MM-dd'T'HH:mm:ss'Z'";
    public static int SENTIMENTS_FETCH_PERIOD = 100;
    public static short FXMindMQL_PORT = 2010;
    public static short AppService_PORT = 2012;
    public static string JOBGROUP_TECHDETAIL = "Technical Details";
    public static string JOBGROUP_OPENPOSRATIO = "Positions Ratio";
    public static string JOBGROUP_EXECRULES = "Run Rules";
    public static string JOBGROUP_NEWS = "News";
    public static string JOBGROUP_THRIFT = "ThriftServer";
    public static string CRON_MANUAL = "0 0 0 1 1 ? 2100";
  }
}
