/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace BusinessObjects
{

  public class SignalInfo 
  {
    public int Id { get; set; }

    public long Flags { get; set; }

    public long ObjectId { get; set; }

    public string RaiseDateTime { get; set; }

    public string Name { get; set; }

    public int Value { get; set; }

    public bool Handled { get; set; }

    public object Data { get; set; }
  }

}
