//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"adviser")]
    public partial class DBAdviser : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fNAME;
        [Size(128)]
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>("NAME", ref fNAME, value); }
        }
        int fMAGICNUMBER;
        public int MAGICNUMBER
        {
            get { return fMAGICNUMBER; }
            set { SetPropertyValue<int>("MAGICNUMBER", ref fMAGICNUMBER, value); }
        }
        DBTerminal fTERMINAL_ID;
        [Association(@"DBAdviserReferencesDBTerminal")]
        public DBTerminal TERMINAL_ID
        {
            get { return fTERMINAL_ID; }
            set { SetPropertyValue<DBTerminal>("TERMINAL_ID", ref fTERMINAL_ID, value); }
        }
        int fSYMBOL_ID;
        [Indexed(Name = @"SYMBOL_ID")]
        public int SYMBOL_ID
        {
            get { return fSYMBOL_ID; }
            set { SetPropertyValue<int>("SYMBOL_ID", ref fSYMBOL_ID, value); }
        }
        byte fRUNNING;
        public byte RUNNING
        {
            get { return fRUNNING; }
            set { SetPropertyValue<byte>("RUNNING", ref fRUNNING, value); }
        }
        byte fDISABLED;
        public byte DISABLED
        {
            get { return fDISABLED; }
            set { SetPropertyValue<byte>("DISABLED", ref fDISABLED, value); }
        }
    }

}
