//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;

namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"adviser")]
    public partial class DBAdviser : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fNAME;
        [Size(128)]
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>("NAME", ref fNAME, value); }
        }
        DBTerminal fTERMINAL_ID;
        [Association(@"DBAdviserReferencesDBTerminal")]
        public DBTerminal TERMINAL_ID
        {
            get { return fTERMINAL_ID; }
            set { SetPropertyValue<DBTerminal>("TERMINAL_ID", ref fTERMINAL_ID, value); }
        }
        DBSymbol fSYMBOL_ID;
        [Association(@"DBAdviserReferencesDBSymbol")]
        public DBSymbol SYMBOL_ID
        {
            get { return fSYMBOL_ID; }
            set { SetPropertyValue<DBSymbol>("SYMBOL_ID", ref fSYMBOL_ID, value); }
        }
        string fTIMEFRAME;
        [Size(64)]
        public string TIMEFRAME
        {
            get { return fTIMEFRAME; }
            set { SetPropertyValue<string>("TIMEFRAME", ref fTIMEFRAME, value); }
        }
        byte fRUNNING;
        public byte RUNNING
        {
            get { return fRUNNING; }
            set { SetPropertyValue<byte>("RUNNING", ref fRUNNING, value); }
        }
        byte fDISABLED;
        public byte DISABLED
        {
            get { return fDISABLED; }
            set { SetPropertyValue<byte>("DISABLED", ref fDISABLED, value); }
        }
        string fSTATE;
        [Size(SizeAttribute.Unlimited)]
        public string STATE
        {
            get { return fSTATE; }
            set { SetPropertyValue<string>("STATE", ref fSTATE, value); }
        }
        DateTime fLASTUPDATE;
        public DateTime LASTUPDATE
        {
            get { return fLASTUPDATE; }
            set { SetPropertyValue<DateTime>("LASTUPDATE", ref fLASTUPDATE, value); }
        }

        int fCLOSE_REASON;
        public int CLOSE_REASON
        {
            get { return fCLOSE_REASON; }
            set { SetPropertyValue<int>("CLOSE_REASON", ref fCLOSE_REASON, value); }
        }

    }

}
