//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"country")]
    public partial class DBCountry : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fALPHA2;
        [Indexed(Name = @"ALPHA2")]
        [Size(2)]
        public string ALPHA2
        {
            get { return fALPHA2; }
            set { SetPropertyValue<string>("ALPHA2", ref fALPHA2, value); }
        }
        byte fIS_ISO3166;
        [Indexed(Name = @"IS_ISO3166")]
        public byte IS_ISO3166
        {
            get { return fIS_ISO3166; }
            set { SetPropertyValue<byte>("IS_ISO3166", ref fIS_ISO3166, value); }
        }
        DBCurrency fCURRENCYID;
        [Association(@"DBCountryReferencesDBCurrency")]
        public DBCurrency CURRENCYID
        {
            get { return fCURRENCYID; }
            set { SetPropertyValue<DBCurrency>("CURRENCYID", ref fCURRENCYID, value); }
        }
        [Association(@"DBPersonReferencesDBCountry")]
        public XPCollection<DBPerson> People { get { return GetCollection<DBPerson>("People"); } }
    }

}
