//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"jobs")]
    public partial class DBJobs : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fCLASSPATH;
        [Size(255)]
        public string CLASSPATH
        {
            get { return fCLASSPATH; }
            set { SetPropertyValue<string>("CLASSPATH", ref fCLASSPATH, value); }
        }
        string fGRP;
        [Size(255)]
        public string GRP
        {
            get { return fGRP; }
            set { SetPropertyValue<string>("GRP", ref fGRP, value); }
        }
        string fNAME;
        [Size(255)]
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>("NAME", ref fNAME, value); }
        }
        string fCRON;
        [Size(128)]
        public string CRON
        {
            get { return fCRON; }
            set { SetPropertyValue<string>("CRON", ref fCRON, value); }
        }
        string fDESCRIPTION;
        [Size(1000)]
        public string DESCRIPTION
        {
            get { return fDESCRIPTION; }
            set { SetPropertyValue<string>("DESCRIPTION", ref fDESCRIPTION, value); }
        }
        string fSTATMESSAGE;
        [Size(SizeAttribute.Unlimited)]
        public string STATMESSAGE
        {
            get { return fSTATMESSAGE; }
            set { SetPropertyValue<string>("STATMESSAGE", ref fSTATMESSAGE, value); }
        }
        DateTime fPREVDATE;
        public DateTime PREVDATE
        {
            get { return fPREVDATE; }
            set { SetPropertyValue<DateTime>("PREVDATE", ref fPREVDATE, value); }
        }
        DateTime fNEXTDATE;
        public DateTime NEXTDATE
        {
            get { return fNEXTDATE; }
            set { SetPropertyValue<DateTime>("NEXTDATE", ref fNEXTDATE, value); }
        }
        string fPARAMS;
        [Size(SizeAttribute.Unlimited)]
        public string PARAMS
        {
            get { return fPARAMS; }
            set { SetPropertyValue<string>("PARAMS", ref fPARAMS, value); }
        }
        byte fDISABLED;
        public byte DISABLED
        {
            get { return fDISABLED; }
            set { SetPropertyValue<byte>("DISABLED", ref fDISABLED, value); }
        }
    }

}
