//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace FXBusinessLogic.fx_mind {

	[Persistent(@"openposratio")]
	public partial class DBOpenPosRatio : XPLiteObject {
		int fID;
		[Key(true)]
		public int ID {
			get { return fID; }
			set { SetPropertyValue<int>("ID", ref fID, value); }
		}
		DateTime fParseTime;
		public DateTime ParseTime {
			get { return fParseTime; }
			set { SetPropertyValue<DateTime>("ParseTime", ref fParseTime, value); }
		}
		int fSymbolID;
		public int SymbolID {
			get { return fSymbolID; }
			set { SetPropertyValue<int>("SymbolID", ref fSymbolID, value); }
		}
		double fLongRatio;
		public double LongRatio {
			get { return fLongRatio; }
			set { SetPropertyValue<double>("LongRatio", ref fLongRatio, value); }
		}
		double fShortRatio;
		public double ShortRatio {
			get { return fShortRatio; }
			set { SetPropertyValue<double>("ShortRatio", ref fShortRatio, value); }
		}
		int fSiteID;
		public int SiteID {
			get { return fSiteID; }
			set { SetPropertyValue<int>("SiteID", ref fSiteID, value); }
		}
	}

}
