//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"terminal")]
    public partial class DBTerminal : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        int fACCOUNTNUMBER;
        public int ACCOUNTNUMBER
        {
            get { return fACCOUNTNUMBER; }
            set { SetPropertyValue<int>("ACCOUNTNUMBER", ref fACCOUNTNUMBER, value); }
        }
        string fBROKER;
        [Size(128)]
        public string BROKER
        {
            get { return fBROKER; }
            set { SetPropertyValue<string>("BROKER", ref fBROKER, value); }
        }
        string fFULLPATH;
        [Size(SizeAttribute.Unlimited)]
        public string FULLPATH
        {
            get { return fFULLPATH; }
            set { SetPropertyValue<string>("FULLPATH", ref fFULLPATH, value); }
        }
        string fCODEBASE;
        [Size(4096)]
        public string CODEBASE
        {
            get { return fCODEBASE; }
            set { SetPropertyValue<string>("CODEBASE", ref fCODEBASE, value); }
        }
        byte fDISABLED;
        public byte DISABLED
        {
            get { return fDISABLED; }
            set { SetPropertyValue<byte>("DISABLED", ref fDISABLED, value); }
        }
        [Association(@"DBAdviserReferencesDBTerminal")]
        public XPCollection<DBAdviser> Advisers { get { return GetCollection<DBAdviser>("Advisers"); } }
    }

}
