//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Solution1.Module.BusinessObjects.fx_mind
{

    [NonPersistent]
    public partial class DBTotalsum : XPLiteObject
    {
        decimal fSUM_BALANCE_;
        [Persistent(@"SUM(BALANCE)")]
        public decimal SUM_BALANCE_
        {
            get { return fSUM_BALANCE_; }
            set { SetPropertyValue<decimal>(nameof(SUM_BALANCE_), ref fSUM_BALANCE_, value); }
        }
    }

}
