//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Solution1.Module.BusinessObjects.fx_mind
{

    [Persistent(@"walletstate")]
    public partial class DBWalletstate : XPLiteObject
    {
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fWALLET_ID;
        [Indexed(Name = @"WALLET_ID")]
        public int WALLET_ID
        {
            get { return fWALLET_ID; }
            set { SetPropertyValue<int>(nameof(WALLET_ID), ref fWALLET_ID, value); }
        }
        DateTime fDATE;
        public DateTime DATE
        {
            get { return fDATE; }
            set { SetPropertyValue<DateTime>(nameof(DATE), ref fDATE, value); }
        }
        decimal fBALANCE;
        public decimal BALANCE
        {
            get { return fBALANCE; }
            set { SetPropertyValue<decimal>(nameof(BALANCE), ref fBALANCE, value); }
        }
        string fcomment;
        [Size(4096)]
        public string comment
        {
            get { return fcomment; }
            set { SetPropertyValue<string>(nameof(comment), ref fcomment, value); }
        }
        string fformula;
        [Size(4096)]
        public string formula
        {
            get { return fformula; }
            set { SetPropertyValue<string>(nameof(formula), ref fformula, value); }
        }
    }

}
