//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FXBusinessLogic.fx_mind
{

    [Persistent(@"wallet")]
    public partial class DBWallet : XPLiteObject
    {
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fNAME;
        [Size(127)]
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>(nameof(NAME), ref fNAME, value); }
        }
        string fSHORT_NAME;
        [Size(64)]
        public string SHORT_NAME
        {
            get { return fSHORT_NAME; }
            set { SetPropertyValue<string>(nameof(SHORT_NAME), ref fSHORT_NAME, value); }
        }
        string fLINK;
        [Size(4096)]
        public string LINK
        {
            get { return fLINK; }
            set { SetPropertyValue<string>(nameof(LINK), ref fLINK, value); }
        }

        byte fRETIRED;
        public byte RETIRED
        {
            get { return fRETIRED; }
            set { SetPropertyValue<byte>("RETIRED", ref fRETIRED, value); }
        }

    }

}
